[package]
name = "shelly-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "CLI for managing and controlling Shelly devices"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "../README.md"
default-run = "shelly"

[[bin]]
name = "shelly"
path = "src/main.rs"

[[bin]]
name = "shelly-cli"
path = "src/main.rs"

[dependencies]
shelly-core = { path = "../core", version = "0.1.12" }
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dirs = "6"
ipnet = { workspace = true }
anyhow = "1"
toml = "0.8"
strsim = "0.11"
crossterm = "0.28"
chrono = { workspace = true }
owo-colors = "4"
netdev = "0.41"
futures = { workspace = true }
